### ISSUE TITLE
Parse TREE into a Python data structure

### ISSUE THREAD

**Issue by blokhin** [thenesterov/treearbo#3]
@thenesterov please, could you help with a Python code to parse this TREE?

```
		<= Head_space $mol_view
			sub /
				<= Head_card $mol_list
					sub / <= Head_title $mol_paragraph
						sub /
							\Does
							<= Head_link $mol_link
								uri <= title_link \
								sub /
									\this material
							\exist?
```

**Comment by thenesterov** [comment]
Hi! What is your problem with treearbo?

You can write your view.tree code to a file, then read it and pass it to the `string_to_tree` function

![image](https://github.com/user-attachments/assets/91900f5f-c9c9-468c-a293-1495d666fe5c)

Or you want to parse it to some custom data structure?

**Comment by blokhin** [comment]
OK, closing, since my question concerns the tree structure itself, not the Python library.
